#!/bin/bash

err=0
trap 'err=1' ERR

yum -y install python-pip python36u python36u-devel python36u-pip
ln -s /usr/bin/python3.6 /usr/bin/python3

dnf install  chicken clojure  erlang-erts fish gtkglext-libs lttng-tools lttng-ust maxima octave octave-devel perl-Digest-CRC pyephem pypy rakudo rust -y
# missing
#dnf allegro5-devel bsd-games clisp dash gforth ncurses-compat-libs pl R-littler rubygem-treetop  -y
#dnf install java-9-openjdk-devel neovim -y

dnf install ant bison bison-devel clang cmake3 emacs-nox \
  flex flex-devel fsharp gc-devel gcc-c++ glib2-devel glibc-devel glibc-devel.i686 -y

ln -s /usr/bin/cmake3 /usr/local/bin/cmake

dnf install nodejs -y

dnf install golang -y

dnf install gmp-c++ gmp-devel libX11-devel -y

dnf install groovy icu java-1.?.0-openjdk ksh -y

dnf install libgcc.i686 lldb lldb-devel mercurial mono-basic mono-complete nasm -y
    
dnf install ocaml patch pcre-devel \
  perl-List-MoreUtils perl-Text-Soundex php-cli python-devel \
  ruby tcsh time vala vim-common wget zsh -y

yum -y install centos-release-scl
yum -y install devtoolset-4-gcc*
HOME=/root scl enable devtoolset-4 bash


dnf install \
  apache-commons-beanutils \
  apache-commons-beanutils-javadoc \
  apache-commons-cli-javadoc \
  apache-commons-codec \
  apache-commons-codec-javadoc \
  apache-commons-collections \
  apache-commons-collections-javadoc \
  apache-commons-collections-testframework \
  apache-commons-compress \
  apache-commons-compress-javadoc \
  apache-commons-configuration \
  apache-commons-configuration-javadoc \
  apache-commons-daemon \
  apache-commons-daemon-javadoc \
  apache-commons-daemon-jsvc \
  apache-commons-dbcp \
  apache-commons-dbcp-javadoc \
  apache-commons-digester \
  apache-commons-digester-javadoc \
  apache-commons-exec \
  apache-commons-exec-javadoc \
  apache-commons-io \
  apache-commons-io-javadoc \
  apache-commons-jexl \
  apache-commons-jexl-javadoc \
  apache-commons-jxpath \
  apache-commons-jxpath-javadoc \
  apache-commons-lang \
  apache-commons-lang3 \
  apache-commons-lang3-javadoc \
  apache-commons-lang-javadoc \
  apache-commons-logging-javadoc \
  apache-commons-net \
  apache-commons-net-javadoc \
  apache-commons-parent \
  apache-commons-pool \
  apache-commons-pool-javadoc \
  apache-commons-validator \
  apache-commons-validator-javadoc \
  apache-commons-vfs \
  apache-commons-vfs-ant \
  apache-commons-vfs-examples \
  apache-commons-vfs-javadoc -y

#  apache-commons-chain \
#  apache-commons-chain-javadoc \
#  apache-commons-collections4 \
#  apache-commons-collections4-javadoc \
#  apache-commons-csv \
#  apache-commons-csv-javadoc \
#  apache-commons-dbutils \
#  apache-commons-dbutils-javadoc \
#  apache-commons-discovery \
#  apache-commons-discovery-javadoc \
#  apache-commons-el \
#  apache-commons-el-javadoc \
#  apache-commons-email \
#  apache-commons-email-javadoc \
#  apache-commons-fileupload \
#  apache-commons-fileupload-javadoc \
#  apache-commons-javaflow \
#  apache-commons-javaflow-ant \
#  apache-commons-javaflow-javadoc \
#  apache-commons-jci \
#  apache-commons-jci-core \
#  apache-commons-jci-eclipse \
#  apache-commons-jci-fam \
#  apache-commons-jci-groovy \
#  apache-commons-jci-janino \
#  apache-commons-jci-javadoc \
#  apache-commons-jci-rhino \
#  apache-commons-jcs \
#  apache-commons-jcs-core \
#  apache-commons-jcs-javadoc \
#  apache-commons-jcs-jcache \
#  apache-commons-jcs-jcache-extras \
#  apache-commons-jcs-jcache-openjpa \
#  apache-commons-launcher \
#  apache-commons-launcher-javadoc \
#  apache-commons-math \
#  apache-commons-math-javadoc \
#  apache-commons-modeler \
#  apache-commons-modeler-javadoc \
#  apache-commons-ognl \
#  apache-commons-ognl-javadoc \
#  apache-commons-pool2 \
#  apache-commons-pool2-javadoc \
#  apache-commons-primitives \
#  apache-commons-primitives-javadoc \

exit "$err"
