#!/bin/bash

# This script is executed at the end
# Add any custom commands you might want to execute here

err=0
trap 'err=1' ERR

python3 -m pip install glances
HOME=/root git config --global core.editor "nano"

exit "$err"
